language: swift
osx_image: xcode9.4
xcode_workspace: RandomUserApp.xcworkspace
xcode_scheme: RandomUserApp
xcode_destination: platform=iOS Simulator,name=iPhone 8,OS=11.4
before_install:
  - pod repo update
after_success:
  - bash <(curl -s https://codecov.io/bash)
