language: swift
osx_image: xcode9.4
script:
  - pod install
  - xcodebuild clean test -workspace RandomUserApp.xcworkspace -scheme RandomUserApp -destination "platform=iOS Simulator,name=iPhone 8,OS=11.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
