//
//  UserListRouter.swift
//  RandomUserApp
//
//  Created Thomas Carayol on 18/09/2018.
//  Copyright © 2018 Thomas Carayol. All rights reserved.
//
//  Template generated by Thomas Carayol @Appstud
//

import UIKit

class UserListRouter: UserListPresenterToRouterProtocol {
    
    static func createModule() -> UIViewController {
        let view = UserListViewController()
        let interactor: UserListPresenterToInteractorProtocol = UserListInteractor()
        let router: UserListPresenterToRouterProtocol = UserListRouter()
        let presenter: UserListViewToPresenterProtocol & UserListInteractorToPresenterProtocol = UserListPresenter(view: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        
        return view
    }
    
    func showDetails(from view: UserListPresenterToViewProtocol?, with userEntity: UserEntity) {
        let nextView = UserDetailsRouter.createModule(userEntity: userEntity)
        if let sourceView = view as? UIViewController {
            sourceView.navigationController?.pushViewController(nextView, animated: true)
        }
    }
}
