//
//  UserDetailsInteractor.swift
//  RandomUserApp
//
//  Created Thomas Carayol on 18/09/2018.
//  Copyright © 2018 Thomas Carayol. All rights reserved.
//
//  Template generated by Thomas Carayol @Appstud
//

import UIKit

final class UserDetailsInteractor: UserDetailsPresenterToInteractorProtocol {

    weak var presenter: UserDetailsInteractorToPresenterProtocol?
}
