//
//  UserDetailsProtocols.swift
//  RandomUserApp
//
//  Created Thomas Carayol on 18/09/2018.
//  Copyright © 2018 Thomas Carayol. All rights reserved.
//
//  Template generated by Thomas Carayol @Appstud
//

import Foundation
import UIKit

/// Delegates from the presenter (business rules) to the view (ui)
protocol UserDetailsPresenterToViewProtocol: class {
    
    /// Show the profile picture
    func show(userPicture: URL)
    
    /// Show the nation flag
    func show(flag: String)
    
    /// Show gender image
    func show(gender: UIImage?)
    
    /// Show name
    func show(name: String)
    
    /// Show email
    func show(email: String)
    
    /// Show cell phone
    func show(cellPhone: String)
    
    /// Show home phone
    func show(homePhone: String)
    
    /// Show location address
    func show(locationAddress: String)
}

/// Delegates from the interactor (api/storage) to the view (ui)
protocol UserDetailsInteractorToPresenterProtocol: class {
}

/// Delegates from the presenter (business rules) to the interactor (api/storage)
protocol UserDetailsPresenterToInteractorProtocol: class {
    var presenter: UserDetailsInteractorToPresenterProtocol?  { get set }
}

/// Delegates from the view (ui) to the presenter (business rules)
protocol UserDetailsViewToPresenterProtocol: class {
    var view: UserDetailsPresenterToViewProtocol? { get set }
    var interactor: UserDetailsPresenterToInteractorProtocol? { get set }
    var router: UserDetailsPresenterToRouterProtocol? { get set }
    
    /// Callback when the view is loaded
    func viewDidLoad()
}

/// Delegates from the presenter (business rules) to the router (navigation)
protocol UserDetailsPresenterToRouterProtocol: class {
    
    /// Initializes and creates a new module
    static func createModule(userEntity: UserEntity) -> UIViewController
}
