//
//  UserDetailsRouter.swift
//  RandomUserApp
//
//  Created Thomas Carayol on 18/09/2018.
//  Copyright © 2018 Thomas Carayol. All rights reserved.
//
//  Template generated by Thomas Carayol @Appstud
//

import UIKit

fileprivate enum UserDetailsRouterIdentifier {
    static let storyboardName = "UserDetails"
}

class UserDetailsRouter: UserDetailsPresenterToRouterProtocol {
    
    static func createModule(userEntity: UserEntity) -> UIViewController {
        let view = UIStoryboard(name: UserDetailsRouterIdentifier.storyboardName, bundle: nil).instantiateInitialViewController() as! UserDetailsViewController
        let interactor: UserDetailsPresenterToInteractorProtocol = UserDetailsInteractor()
        let router: UserDetailsPresenterToRouterProtocol = UserDetailsRouter()
        let presenter: UserDetailsViewToPresenterProtocol & UserDetailsInteractorToPresenterProtocol = UserDetailsPresenter(view: view, interactor: interactor, router: router, userEntity: userEntity)
        
        view.presenter = presenter
        interactor.presenter = presenter
        
        return view
    }
}
