//
//  UserDetailsPresenter.swift
//  RandomUserApp
//
//  Created Thomas Carayol on 18/09/2018.
//  Copyright © 2018 Thomas Carayol. All rights reserved.
//
//  Template generated by Thomas Carayol @Appstud
//

import UIKit

final class UserDetailsPresenter: UserDetailsViewToPresenterProtocol {

    weak var view: UserDetailsPresenterToViewProtocol?
    var interactor: UserDetailsPresenterToInteractorProtocol?
    var router: UserDetailsPresenterToRouterProtocol?

    var data: UserEntity
    
    init(view: UserDetailsPresenterToViewProtocol?, interactor: UserDetailsPresenterToInteractorProtocol?, router: UserDetailsPresenterToRouterProtocol?, userEntity: UserEntity) {
        self.view = view
        self.interactor = interactor
        self.router = router
        self.data = userEntity
    }
    
    func viewDidLoad() {
        
        // Flag
        self.view?.show(flag: self.data.nat.flag())
        
        // Name
        let name = "\(self.data.name.title.capitalized) \(self.data.name.first.capitalized) \(self.data.name.last.capitalized)"
        self.view?.show(name: name)
        
        // Email
        self.view?.show(email: self.data.email)
        
        // Cell phone
        self.view?.show(cellPhone: self.data.cell)
        
        // Home phone
        self.view?.show(homePhone: self.data.phone)
        
        // Picture
        if let url = URL(string: self.data.picture.large) {
            self.view?.show(userPicture: url)
        }
        
        // Gender
        self.view?.show(gender: UIImage(named: self.data.gender.rawValue))
        
        // Location
        var locationAddress = ""
        if let countryName = (Locale.current as NSLocale).displayName(forKey: .countryCode, value: self.data.nat) {
            locationAddress = "\(self.data.location.street.capitalized)\n\(self.data.location.postcode) \(self.data.location.city.capitalized)\n\(self.data.location.state.capitalized)\n\(countryName)"
        } else {
            locationAddress = "\(self.data.location.street.capitalized)\n\(self.data.location.postcode) \(self.data.location.city.capitalized)\n\(self.data.location.state.capitalized)"
        }
        self.view?.show(locationAddress: locationAddress)
    }
}

extension UserDetailsPresenter: UserDetailsInteractorToPresenterProtocol {
    
}
